### ISSUE TITLE
Changing the upstream controller's goal status in chained controllers

### ISSUE THREAD

**Issue by samialperen** [ros-controls/ros2_controllers#1072]
Imagine a chained controller: JTC (upstream) + admittance (downstream)

Is there a way that the downstream chained controller (admittance controller) can set upstream goal (JTC's goal) as successful? Otherwise, admittance might want to do nothing, however that is not going to affect JTC's goal which will eventually timeout that is undesired.

**Comment by christophfroehlich** [comment]
No, this is not possible at the moment. The action itself is not shared between controllers.

**Comment by christophfroehlich** [comment]
Per default it is even not possible to share any information between controller. However, it now should be possible to use state interfaces by the chained controller to push information from the downstream to the upstream controller.
