### ISSUE TITLE
Move `descripion.hpp` into `test_robot_hardware` package and update all controllers

### ISSUE THREAD

**Issue by destogl** [ros-controls/ros2_controllers#115]
should be moved into `test_robot_hardware` package.
will be done in follow up PR.

_Originally posted by @destogl in https://github.com/ros-controls/ros2_controllers/pull/99#discussion_r532403096_

**Comment by bmagyar** [comment]
Superseded by #113

**Comment by destogl** [comment]
Oh Sorry!
