### ISSUE TITLE
Problem remapping joint_state_broadcaster

### ISSUE THREAD

**Issue by brennand** [ros-controls/ros2_controllers#1246]
**Describe the bug**
I have 2 control managers and want to remap one of the joint_state_broadcaster output topic to `/joint_states`.  I've tried a lot of different combinations and still no luck.

This is what my launch file looks like.

```
    gripper_joint_state_broadcaster_spawner = Node(
        package="controller_manager",
        executable="spawner",
        namespace="gripper_ns",
        arguments=[
            "joint_state_broadcaster",
            "--controller-manager",
            "/gripper_ns/controller_manager",
        ],
        remappings=[
            ("/gripper_ns/joint_states", "/joint_states"),
        ],
        output={"both": "screen"},
        emulate_tty=True,
    )
```

**Expected behavior**
I would expect that the `joint_states` topic should change in `ros2 topic list`

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Version: humble

**Comment by christophfroehlich** [comment]
You have to add the remapping to the ros2_control_node, because the node od the controller will be created from there. The spawner is only a helper script which interacts with the controller_manager (also launched from ros2_control_node).

**Comment by brennand** [comment]
@christophfroehlich , Thank you for your fast reply.
