### ISSUE TITLE
About min_acceleration when reversing

### ISSUE THREAD

**Issue by otamachan** [ros-controls/ros2_controllers#1317]
**Is your feature request related to a problem? Please describe.**
I am using the `diff_drive_controller`, and I want the robot to accelerate slowly when speeding up and decelerate quickly to come to a stop. To achieve this, I have set `min_acceleration` and `max_acceleration`, and the robot behaves as expected when moving forward. However, when reversing, the acceleration is fast, and the deceleration is slow, so it does not work as expected.

**Describe the solution you'd like**
Would it be better to reverse the handling of `min_acceleration` and `max_acceleration` when reversing?

**Describe alternatives you've considered**

**Additional context**
I found the similar issue in ros_controllers(https://github.com/ros-controls/ros_controllers/issues/290)

**Comment by otamachan** [comment]
might be related to https://github.com/ros-controls/control_toolbox/pull/212

**Comment by christophfroehlich** [comment]
Thanks for reporting this, I'll have a look and fix that maybe with (or after) the PR in control_toolbox. We have a newer implementation of the speed limiter in the tricycle_controller package, where there is also a min_deceleration and max_deceleration parameter. Maybe we should consider using that one for all controllers, but it has different parameters and I'm not sure if we should change the well-established ones from diff_drive_controller.

**Comment by christophfroehlich** [comment]
@otamachan could you have a look at #1315 please and see if it solves your problem?

**Comment by otamachan** [comment]
Great!! I'll try. Thank you!
