### ISSUE TITLE
Publishing `JointTrajectoryControllerState` from `diff_drive_controller`

### ISSUE THREAD

**Issue by nishino-pfr** [ros-controls/ros2_controllers#1318]
**Is your feature request related to a problem? Please describe.**
In ROS1, the `diff_drive_controller` had an option to publish `JointTrajectoryControllerState`, which was very useful for checking motor control performance.

**Describe the solution you'd like**
It would be great to add this feature to the ROS2 `diff_drive_controller` as well.

**Describe alternatives you've considered**

**Additional context**
Related to https://github.com/ros-controls/ros_controllers/pull/408

**Comment by christophfroehlich** [comment]
Why have you closed the issue, had you found a workaround for that?

FYI: We plan to integrate debug mechanisms like [pal_statistics](https://github.com/pal-robotics/pal_statistics) or [data_tamer](https://github.com/ros-controls/ros2_control/pull/1255), or as simple topic https://github.com/ros-controls/ros2_control/pull/1244
This means that it won't be necessary to add such types of publishers for debugging to every controller.

**Comment by bmagyar** [comment]
We also have controller_state published from all steering controllers and
the JTC too. The diff drive controller may not have it but if it did, would
that be helpful?
