### ISSUE TITLE
Missing header files

### ISSUE THREAD

**Issue by JaehyunShim** [ros-controls/ros2_controllers#134]
Hi, 

Please check out the following [link](https://github.com/ros-controls/ros2_controllers/blob/master/diff_drive_controller/src/diff_drive_controller.cpp#L26).
Line 26, 27 do not exist in the ros2_control repository. Where are they coming from? 

Jaehyun

**Comment by destogl** [comment]
Hi @JaehyunShim,

they are not coming from anywhere. The diff controller is currently not functioning and it is not build (it has COLCON_IGNORE) file in it.
#128 should "revive" diff drive controller

**Comment by bmagyar** [comment]
I've just merged the diff drive,you can use the master branch but as Denis said previously, please look first before asking.
