### ISSUE TITLE
Admittance Controller: parameter robot_description not set

### ISSUE THREAD

**Issue by mhubii** [ros-controls/ros2_controllers#1379]
Hi All,

trying to run the admittance controller. (`Ubuntu 24.04`, `rolling`). Receiving:

```shell
[ros2_control_node-3] [ERROR] [1732101243.342290020] [kinematics_interface_kdl]: parameter robot_description not set
```

The calling order:
1. https://github.com/ros-controls/ros2_controllers/blob/79358e38100139cd1d91ba8d090a388677d464b3/admittance_controller/src/admittance_controller.cpp#L284

2. https://github.com/ros-controls/ros2_controllers/blob/79358e38100139cd1d91ba8d090a388677d464b3/admittance_controller/include/admittance_controller/admittance_rule_impl.hpp#L62

3. Triggered here:
https://github.com/ros-controls/kinematics_interface/blob/822cff404424004d646d384c8dfedb226de2b54a/kinematics_interface_kdl/src/kinematics_interface_kdl.cpp#L42

The `controller_manager` is namespaced.

Any idea? Thank you!

**Comment by christophfroehlich** [comment]
Have you built the rolling stack from source? We recently changed this with https://github.com/ros-controls/ros2_controllers/pull/1247, but the binaries haven't been synced yet.

**Comment by mhubii** [comment]
hi @christophfroehlich and thank you for the hint. Been using distributed binaries

**Comment by mhubii** [comment]
I presume that this is fixed, just not in the binaries yet. Closing.

**Comment by bmagyar** [comment]
Correct. It was flagged up by the tests straight away. We still support getting the description from params but it's only for backward compatibility for older distros.
