### ISSUE TITLE
Problem remapping joint_trajectory_controller

### ISSUE THREAD

**Issue by stocks-yuan** [ros-controls/ros2_controllers#1423]
**Describe the bug**
I have 2 control managers and want to remap one of the joint_trajectory_controller action 
`leftArm/joint_trajectory_controller/follow_joint_trajectory` to `joint_trajectory_controller/follow_joint_trajectory` (leftArm is namespace).I've tried a lot of different combinations and still no luck.

This is what my launch file looks like.
```
    ur_control_node = Node(
        package="ur_robot_driver",
        executable="ur_ros2_control_node",
        namespace="leftArm",
        parameters=[
            robot_description,
            update_rate_config_file,
            ParameterFile(initial_joint_controllers, allow_substs=True),
        ],
        remappings=[
            ("/joint_trajectory_controller/follow_joint_trajectory", "/leftArm/joint_trajectory_controller/follow_joint_trajectory"),
        ],
        output="screen",
        condition=UnlessCondition(use_fake_hardware),
    )
```

**Expected behavior**
I would expect that the `leftArm/joint_trajectory_controller/follow_joint_trajectory`  action should change to `joint_trajectory_controller/follow_joint_trajectory`

**Environment (please complete the following information):**
 - OS: Ubuntu22.04
 - Version humble

**Comment by christophfroehlich** [comment]
This is not related with this repository but a missing feature of rclcpp.
See the solution of manually remap topics/services related to an action
https://github.com/ros2/ros2/issues/1312#issuecomment-1705521109
