### ISSUE TITLE
Create joint_state_broadcaster to replace joint_state_controller

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros2_controllers#158]
We've recently decided to suffix all not-really-controllers (joint_state_controller, force_torque_controller, etc from ROS1) with *broadcaster* to follow the nomenclature of tf and to avoid name clashes with publishers (ROS) and observers (control theory). 

Task is considered complete when
* there's a new package `joint_state_broadcaster`, with all references to `joint_state_controller` gone
* the `joint_state_controller` package still exists but includes a very minimal amount of code to make the old name still available -> you can probably pull this off by tweaking the `joint_state_plugin.xml` file and without having to have additional C++ code
* add a deprecation note to `joint_state_plugin.xml` and other visible places (if any) to `joint_state_controller`
* one can load either `joint_state_broadcaster` or `joint_state_controller` and both produce the same result

Supersedes #110

**Comment by matthew-reynolds** [comment]
I don't have permissions in this repo to self-assign, but I will take this on.

**Comment by matthew-reynolds** [comment]
I think this can be closed
