### ISSUE TITLE
[JointTrajectoryController] Reconsider memory operation in the Starting, Update and Stoping methods

### ISSUE THREAD

**Issue by destogl** [ros-controls/ros2_controllers#183]
As @jordan-palacios wrote: current implementation of JTC is not real-time safe. The memory operations, i.e. vector manipulations and resizing has to be reconsidered. See below his comment:

I know this is not strictly related to this PR, but we can't be resizing vectors on every loop. This is not real-time safe.

@bmagyar Maybe we should open a follow up PR?

_Originally posted by @jordan-palacios in https://github.com/ros-controls/ros2_controllers/pull/140#discussion_r627251793_

**Comment by christophfroehlich** [comment]
The original code referenced by this comment is not available any more. I allow myself to close this in favor of #392.
