### ISSUE TITLE
Request: ackermann_steering_controller

### ISSUE THREAD

**Issue by Timple** [ros-controls/ros2_controllers#194]
Feature request: Ackermann steering controller

It seems it was available in [ros1](https://github.com/ros-controls/ros_controllers/tree/noetic-devel/ackermann_steering_controller). However the implementation seemed [off](https://github.com/ros-controls/ros_controllers/issues/412). 

Also support for front-wheel drive seems to be [missing](https://github.com/ros-controls/ros_controllers/blob/a075bc36ebf5b81a7dafe911907cc1b781dd0185/ackermann_steering_controller/src/ackermann_steering_controller.cpp#L334). The front wheels have a different radius they drive about, so the velocity is slightly different. But in case of e.g. a forklift this becomes significant.

**Comment by Timple** [comment]
I'm rather new to `ros2_control` and this requires several interfaces on velocity and position level.

If somebody is willing to give a head-start by providing the cpp/hpp dummy classes, I'm happy to finish the work with all logic/algorithms involved!

**Comment by bmagyar** [comment]
I think the work here would be porting the existing controller to ros2. The tests are where a lot of complexity lies but good news is that they are basically copies of the diff drive tests. Bad news is that we never got around to porting "the good stuff" when it comes to tests.

**Comment by destogl** [comment]
> If somebody is willing to give a head-start by providing the cpp/hpp dummy classes, I'm happy to finish the work with all logic/algorithms involved!

Are you still interested into this? I could find some time to set up initial files and tests.

**Comment by Timple** [comment]
Yup, this would still be on the 'todo' list.

Altough it also seems that it would just be a subset of this: https://discourse.ros.org/t/independent-swerve-steering-controller-for-ros-control/21534/1

Eitherway having the dummy classes and tests would really help!

**Comment by tomlogan501** [comment]
+1 for swerve controller and four wheel controller

**Comment by samuk** [comment]
> > If somebody is willing to give a head-start by providing the cpp/hpp dummy classes, I'm happy to finish the work with all logic/algorithms involved!
> 
> @Timple Are you still interested into this? I could find some time to set up initial files and tests.

@destogl do you think you may still find time for this?

**Comment by christophfroehlich** [comment]
I think the requested controller was added with #484. If something is missing, please open a more specific issue.
