### ISSUE TITLE
wrong namespace set for individual controller packages

### ISSUE THREAD

**Issue by Karsten1987** [ros-controls/ros2_controllers#21]
Labeling it as a bug is maybe a bit much, but the namespaces are of each individual ros2 controller should match its package name namespace. 
So, e.g. instead of using `ros_controllers` the joint state controller should use `joint_state_controller` as its namespace.

**Comment by jordan-palacios** [comment]
Ah my bad, it was my intention to do what you precisely describe here. I even adapted the control access definitions to show the correct namespace.

https://github.com/ros-controls/ros2_controllers/blob/40b858bc26955ae50e6bb88c676a1c4e6f6c99d1/joint_state_controller/include/joint_state_controller/joint_state_controller.hpp#L16

I ended up forgetting to rename the actual namespace name. Will fix!
