### ISSUE TITLE
JTC Open-loop Control Mode: Should `last_commanded_state_` here be reduced to existing state interface from the hardware? Or is it OK to internally manage more control-states then can be received from hardware?

### ISSUE THREAD

**Issue by destogl** [ros-controls/ros2_controllers#214]
Should `last_commanded_state_` here be reduced to existing state interface from the hardware? Or is it OK to internally manage more control-states then can be received from hardware?

_Originally posted by @destogl in https://github.com/ros-controls/ros2_controllers/pull/189#r642045259_

**Comment by christophfroehlich** [comment]
@destogl could you please explain what you meant here? I'd be happy to implement that.

You mean that it should not set the `point_before_trajectory_msg` from the commands, if there is no state interface with identical hardware interface for the joint? What would be the alternative? Just use the first entry of the trajectory message?

**Comment by destogl** [comment]
Not worth to take care of it.
