### ISSUE TITLE
missing pluginlib xml files for each controller

### ISSUE THREAD

**Issue by Karsten1987** [ros-controls/ros2_controllers#22]
With #19 the individual controllers can't be loaded anymore as the according `plugin.xml` file is missing. 

@jordan-palacios : How did you test to load the controllers in the controller manager? Maybe I am missing something here.

**Comment by jordan-palacios** [comment]
> @jordan-palacios : How did you test to load the controllers in the controller manager? Maybe I am missing something here.

Controller loading was validated using the [test_controller](https://github.com/ros-controls/ros2_control/blob/master/controller_manager/test/test_controller/test_controller.hpp).

There are no tests for controller loading of each individual controller though and I missed adding the `plugin.xml` files in #19. I'll fix that and also add loading tests for each controller.
