### ISSUE TITLE
JointGroupPositionController fails to initialize on Rolling due to rclcpp "undeclare_parameter" API change

### ISSUE THREAD

**Issue by schornakj** [ros-controls/ros2_controllers#221]
There have already been [some fixes to other controllers](https://github.com/ros-controls/ros2_controllers/pull/199) for the rclcpp parameter API changes. Currently (as of 0.4.1) the `JointGroupPositionController` fails to initialize because it tries to undeclare a statically-typed parameter at [these lines](https://github.com/ros-controls/ros2_controllers/blob/6a53981982eeac1822bfca8e9d5e40156870c0b1/position_controllers/src/joint_group_position_controller.cpp#L41-L47), which produces an error:

```
[ros2_control_node-1] [INFO] [1628693935.184140389] [controller_manager]: Loading controller 'position_controller'
[ros2_control_node-1] Exception thrown during init stage with message: parameter 'interface_name' has invalid type: cannot undeclare an statically typed parameter 
[ros2_control_node-1] [ERROR] [1628693935.194137855] [controller_manager]: Could not initialize the controller named 'position_controller'
```

I wanted to get some additional context and input before I try to fix this myself: why is it necessary to undeclare the `interface_name` parameter declared by `ForwardCommandController`, and does anyone else already have a fix in mind?

**Comment by gc-robotics** [comment]
I am facing the same issue.

Exception thrown from the following line:
`    // undeclare interface parameter used in the general forward_command_controller
    get_node()->undeclare_parameter("interface_name");`

**Comment by gc-robotics** [comment]
Have just seen the PR. Will wait for the approval. Thanks @schornakj .
