### ISSUE TITLE
diff_drive_controller shall accept velocity feedback from motors

### ISSUE THREAD

**Issue by roncapat** [ros-controls/ros2_controllers#229]
At a certain point in ROS1 implementation, `estimate_velocity_from_position` parameter switch was inserted, and odometry could also be computed by integration of velocity values coming directly from motors.

In ROS2, this in not an option. Although somewhere it is written that the controller works "through a velocity interface" this is true only for the input chain, not the feedback one.

I propose a port of the feature also in ROS2 , and at least specify clearly what are the required Hardware Interfaces (in/out) for this controller in the documentation.

**Comment by bmagyar** [comment]
Yes! I'm quite sad that we never got to port more of the diff drive functionality over to ROS2 as we are still fairly busy with the framework itself. I'd be very happy to review some PRs for this though!

**Comment by roncapat** [comment]
I searched again the sources of the implementation I mentioned in the opening of this issue. From mobile, didn't found yet the code I swear to have seen at some time in some branch of ros_controllers official repo, but I remember it was something very similar to what can be seen here:
https://github.com/clearpathrobotics/ros_controllers/pull/10

Starting from this code, I think that in the next week I can open a draft PR, or maybe even already test it in my company on our retrofitted Seekur Jr Rover.

**Comment by roncapat** [comment]
Closing since #260 got merged.
