### ISSUE TITLE
[DiffDriveController] Rename "velocity" to "command" or even better "velocity_command"

### ISSUE THREAD

**Issue by destogl** [ros-controls/ros2_controllers#270]
Current name “velocity” is confusing and ambiguous.

> I am actually proposing to rename the "velocity" to "command" or something like this.

_Originally posted by @destogl in https://github.com/ros-controls/ros2_controllers/pull/260#discussion_r752227043_

**Comment by bailaC** [comment]
@destogl this issue can be closed I guess...found velocity_command in current code.
