### ISSUE TITLE
Wrong integration of velocity feedback in diff_drive_controller

### ISSUE THREAD

**Issue by roncapat** [ros-controls/ros2_controllers#286]
See https://github.com/ros-controls/ros2_controllers/pull/260#discussion_r787651764
Thanks to @wmmc88 for spotting this bug.

**Comment by ros-gy** [comment]
Would the fix for this issue to change line 220/221 (depending on master/galactic branch) to:

`odometry_.updateFromVelocity(left_feedback_mean*update_dt.seconds(), right_feedback_mean*update_dt.seconds(), current_time);`
