### ISSUE TITLE
Ackermann Steering Controller

### ISSUE THREAD

**Issue by armuren** [ros-controls/ros2_controllers#288]
## Background

Aside from issue #264 have there been any attempts at an ackermann controller for ros2-controllers?  From what I can tell of that issue, the port is no longer being worked on.

Here's what I currently have:

1. A project with a URDF description that is gazebo valid and spawns a simple 4 wheel robot
2. Integration with gazebo_ros2_control linking to the ros2-control Diff Drive controller config
3. the small city world in Gazebo with a few cars, streets, stop signs, traffic lights, etc

My plan is to follow the instructions in this [comment](https://github.com/ros-controls/ros2_controllers/issues/264#issuecomment-996646394) and begin attempting to implement an ackerman steering controller.  

If I am successful in this, I may then open a PR for the controller, plus a PR in ros-control-demos with the content I described above.

Any input, feedback, or direction is highly welcomed!

**Comment by bmagyar** [comment]
This would be a very welcome change, thank you! Would you mind posting the same message in #264  that you are essentially planning to take over this effort to notify the people over there? And this issue could be closed as a duplicate of that.

**Comment by aboarya** [comment]
Sure thing! Will do...

**Comment by tonynajjar** [comment]
Hi @armuren, I'm sure many are impatiently waiting for your contributions! Could you share any updates on your progress?

**Comment by tonynajjar** [comment]
We waited so impatiently that we decided to give it a try ourselves :smile: : https://github.com/ros-controls/ros2_controllers/pull/344/files
It's not exactly ackermann but I think with minor changes it could also work for ackermann as the kinematics are very similar as far as I know

**Comment by armuren** [comment]
@tonynajjar my apologies! I got distracted and was not able to follow up on this.  I will close this PR
