### ISSUE TITLE
Clang Format in pre-commit file could be broken on newer systems

### ISSUE THREAD

**Issue by erickisos** [ros-controls/ros2_controllers#295]
## Context

Hey folks, I'm having problems doing a simple commit because of our pre-commit configuration, there is one step in which we have defined `clang-format-10`, and by default at least on my machine, brew is pulling version 13 of that program.

So, my question is, do you think it is worth just removing that kind of restriction from our pre-commit file? or are we using some specific settings from that version?
Btw, I already tried removing that specification from pre-commit, and now I can run the process without problems.

I can do this in a separate PR if you want, or if you think this would be good as a "first issue", feel free to edit the Issue and keep it open for someone else.

## Environment

- OS: macOS
- Version: 11.6.3
- Architecture: arm64

**Comment by erickisos** [comment]
Just adding some extra information:

I tried running the pre-commit tasks with clang-format 13, and because we are using the [Allman specification for "BreakBeforeBraces"](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) the version solves everything "correctly".

However, in the pipeline of #296 it seems like clang-format-10 has [this bug](https://bugs.llvm.org/show_bug.cgi?id=27640) and doesn't achieve to format lambda functions in the "expected way", so what do you think about this? which kind of formatting do you prefer? and Idk if this is just a problem for macOS arm, or if is a problem for everyone using brew.

Looking at this context, I think it would be better to really separate those concerns in another PR.

**Comment by bmagyar** [comment]
The best way would really be to use a container-based clang-format like the
rest of the tools tend to be with precommit  (or virtualenv). I'm also not
happy with the system dependencies spilling into the precommit file but
currently that seemed to be the best option. Please note that when it comes
to CI the only option we really have is some Linux, specifically Ubuntu as
it's the most native ROS platform.

OSX got demoted to tier3 platforms as it seemed even less reliable than
Windows (I know, right??).

I think the best way forward would be to use a containerized clang-format
to ensure everyone always uses the exact same version. Did you check those
options back in the day, @destogl?

**Comment by destogl** [comment]
> I think the best way forward would be to use a containerized clang-format to ensure everyone always uses the exact same version. Did you check those options back in the day, @destogl?

I didn't, but it would be a great thing to do.
