### ISSUE TITLE
[CI] colcon-mixin for coverage-gcc wrongly specified in action-ros-ci

### ISSUE THREAD

**Issue by aprotyas** [ros-controls/ros2_controllers#305]
**Describe the bug**

The `colcon-mixin-name` option used to specify the `coverage-gcc` mixin in [invoking `action-ros-ci` for `ros-tooling-ci`](https://github.com/ros-controls/ros2_controllers/blob/b9ccf04aa95203e37077f297ddcf9f933ef464fa/.github/workflows/ci.yml#L55) has been removed from said Github action in https://github.com/ros-tooling/action-ros-ci/pull/591, with `colcon-defaults` being suggested as the way to specify mixins instead.

As such, the `coverage-gcc` mixin doesn't actually get added.

**To Reproduce**
Look at any ros-tooling ci log. Here's a linked example: https://github.com/ros-controls/ros2_controllers/runs/5307042090?check_suite_focus=true#step:3:1

**Expected behavior**
The `coverage-gcc` mixin gets correctly added and that there are no warnings in CI logs.

**Environment (please complete the following information):**
Github actions environment specified for ros-tooling ci
 - OS: Ubuntu 20.04 LTS
 - Version galactic

**Additional context**
The problem can be fixed with the following patch to .github/workflows/ci.yml, and has been submitted in https://github.com/ros-controls/ros2_controllers/pull/306.

```patch
-          colcon-mixin-name: coverage-gcc
+          colcon-defaults: |
+            {
+              "build": {
+                "mixin": ["coverage-gcc"]
+              }
+            }
```

**Comment by christophfroehlich** [comment]
fixed with #317
