### ISSUE TITLE
RealtimeBuffer has no member named reset

### ISSUE THREAD

**Issue by jackcenter** [ros-controls/ros2_controllers#322]
**Describe the bug**
When doing a clean build on Galactic I get the following error: 
```
ros2_controllers/forward_command_controller/src/forward_command_controller.cpp:127:19: 
error: ‘class realtime_tools::RealtimeBuffer<std::shared_ptr<std_msgs::msg::Float64MultiArray_<std::allocator<void> > > >’ has no member named ‘reset’
  127 |   rt_command_ptr_.reset();

ros2_controllers/forward_command_controller/src/forward_command_controller.cpp:136:19: 
error: ‘class realtime_tools::RealtimeBuffer<std::shared_ptr<std_msgs::msg::Float64MultiArray_<std::allocator<void> > > >’ has no member named ‘reset’
  136 |   rt_command_ptr_.reset();
```
I can fix the error by reverting #283.

**To Reproduce**
1. Do a clean build with the galactic branch.

**Expected behavior**
No errors on build

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: Galactic

**Comment by aprotyas** [comment]
What version of realtime_tools do you have? I can build cleanly on the latest [Galactic docker image](https://hub.docker.com/layers/ros/library/ros/galactic/images/sha256-5e94a4cb9fa079ba2d516530161f629ff0c59650cf869bf63a5c19a4f9f0dd49?context=explore) with:
```bash
# apt list ros-galactic-realtime-tools
Listing... Done
ros-galactic-realtime-tools/focal,now 2.2.0-1focal.20220211.053905 amd64 [installed]
```

**Comment by jackcenter** [comment]
Thanks for the quick response! Looks like I had two installed and was using the wrong one, this fixed it for me. Thanks again!
