### ISSUE TITLE
Diff drive controller build issue:   get_prefix_name

### ISSUE THREAD

**Issue by AndyZe** [ros-controls/ros2_controllers#378]
I'm on ROS2 Rolling and just did a rebase on the `master` branch.

Build error:

```
  /home/runner/work/ros2_controllers/ros2_controllers/.work/target_ws/src/ros2_controllers/diff_drive_controller/src/diff_drive_controller.cpp:641:26:error: ‘const class hardware_interface::LoanedCommandInterface’ has no member named ‘get_prefix_name’
    641 |         return interface.get_prefix_name() == wheel_name &&
```

You can see it in the CI log here:

https://github.com/ros-controls/ros2_controllers/runs/7179872463?check_suite_focus=true

**Comment by bmagyar** [comment]
Get the latest ros2_control (you may need to uninstall the last release if
the cmake gods are not happy with you) and that should fix it.
