### ISSUE TITLE
joint_trajectory_controller::test_trajectory_controller.cpp tests timeout

### ISSUE THREAD

**Issue by jaron-l** [ros-controls/ros2_controllers#447]
**Describe the bug**
joint_trajectory_controller::test_trajectory_controller.cpp::PositionTrajectoryControllers/TrajectoryControllerTestParameterized.configure_state_ignores_commands/0 times out when running from commit b157c0d35d42f850dbb48f1d35f91796344c2a5c

**To Reproduce**
1. checkout commit b157c0d35d42f850dbb48f1d35f91796344c2a5c
2. build
3. run all tests in the joint_trajectory_controller package

**Expected behavior**
Tests should pass

**Environment (please complete the following information):**
 - OS: ubuntu 22.04.1 LTS (Jammy Jellyfish)
 - Version: rolling
- Running in a docker.io/ros:rolling docker container

**Additional context**
Found by running git bisect. @tylerjw You might be able to debug this fastest as the above mentioned commit is authored by you, though others are mentioned in the commit.

**Comment by christophfroehlich** [comment]
Closing because I can't reproduce this any more. 

There is no hint in current test logs, the old logs are not accessible any more, and adding a 

`  std::cout << "End of test" << std::endl;`

to the specific test is printed to the log file.
