### ISSUE TITLE
Bring diff_drive_controller to master branch

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros2_controllers#46]
Plenty of code found here: https://github.com/ros-controls/ros2_controllers/tree/diff-drive

Short todo list:
* [x] Review licenses, AFAIK most of this code originated from PAL, if licenses were skewed by contributors on this branch, you may want to rectify that (and should have all the power to do so)
* [x] Rebase to latest master
* [x] I'd like if we could *actually* review this chunk by chunk, if you could split it into 3 evenly-sized PR-s, that'd be great
* [x] Ensure that appropriate test coverage is there
* [x] In order to minimize the size of dependencies, please remove the boost dependency and re-implement the equivalent functionality `boost::clamp` and `boost::rolling_mean` in a new file called `miniboost.hpp`.

**Comment by jordan-palacios** [comment]
Can we close this? diff_drive_controller was merged in #67.

**Comment by bmagyar** [comment]
Thanks, indeed this was done!
