### ISSUE TITLE
[JTC] Jerky motion with Franka Emika Panda - Effort interface

### ISSUE THREAD

**Issue by tingelst** [ros-controls/ros2_controllers#673]
**Describe the bug**
I have a Franka Emika Panda setup working with Humble. With the original `joint_effort_trajectory_controller` I get smooth motions in MoveIt and when using `rqt_joint_trajectory_controller`. However, when using the `joint_trajectory_controller` here on the `humble` branch I get jerky motions.

**To Reproduce**
1. Run this PR on your system: https://github.com/frankaemika/franka_ros2/pull/10
2. Start MoveIt or `rqt_joint_trajectory_controller` and move the robot
3. Robot moves with jerky motions

**Expected behavior**
The robot should move smoothly.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version: Humble

**Comment by tingelst** [comment]
Seems like I am not the only one having this issue: https://github.com/frankaemika/franka_ros2/pull/10#issuecomment-1594526860

**Comment by tingelst** [comment]
Thank you, @JafarAbdi!  I can confirm that I got the expected behavior, that is, the robot motion smooth, when I checked out the parent commit: https://github.com/ros-controls/ros2_controllers/commit/ce0aeb29e8b42a030248c95a6ee3ec0e99c5e80b. I will continue testing tomorrow.

**Comment by tingelst** [comment]
@JafarAbdi, I have found the source of the jerky/wobbly motion. The bug was introduced in https://github.com/ros-controls/ros2_controllers/commit/ce0aeb29e8b42a030248c95a6ee3ec0e99c5e80b as you expected. The velocity error term is not computed when using an effort command interface, only for velocity command interfaces. This can be fixed by changing [this line](https://github.com/ros-controls/ros2_controllers/blob/6c979091a7e6477963226765a23ecadd33a70d3a/joint_trajectory_controller/src/joint_trajectory_controller.cpp#LL136C9-L136C38) from
```cpp
    if (has_velocity_state_interface_ && has_velocity_command_interface_)
```
to
```cpp
    if (has_velocity_state_interface_ && (has_velocity_command_interface_ || has_effort_command_interface_))
```

I'll submit at PR for this.

I also have a problem with non-zero effort commands commanded after execution as mentioned in issue https://github.com/ros-controls/ros2_controllers/issues/671#issue-1757801230, but I'll take that discussion there.

**Comment by JafarAbdi** [comment]
@tingelst This should be closed since the bug is fixed in the main branch, right?

**Comment by tingelst** [comment]
@JafarAbdi, yes indeed. Thank you for the help in tracking this down.
