### ISSUE TITLE
Best way to pipe sensor data(temp, range) from a hardware interface

### ISSUE THREAD

**Issue by gseqBE** [ros-controls/ros2_controllers#685]
This is more of a question.  We have a hardware interface that connects to a platform with motor drives and sensors.
This connection could be Ethernet or CAN, but we use CAN at the moment.

We can currently connect to the drives via CAN by designing a hardware interface. There are two motor drives setup as joints and a few sensors(eg temperature). We have the following working:
- A Diff-Drive-Controller to send data to the motor joints. These are simple to setup as the joints take in a position or velocity
- A Joint State Broadcaster that publishes joint states over /joint_states

How do we get sensor data broadcasted, like a temperature, input status or range? ROS2_controllers only has the IMU and FTS broadcasters, but not one for generic sensors listed above. I have seen the UR_controller implementation using a [gpio_controller](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/main/ur_controllers/src/gpio_controller.cpp)

I see a few options, but need input on selecting the best one:

1. Create a sensor broadcaster like the FTS broadcaster(edit: and the UR gpio controller above) and publish data and a topic of choice.
2. Make the sensor a part of a joint. Even if it is not a joint, it could be made a non-revolute joint and treated as one. Then make it a state_interface. This way the joint state broadcaster picks it up.
3. Any other option.

Thank you!

**Comment by bmagyar** [comment]
You nailed it! This is what broadcasters are for! If you can't find the ones you need, write a new one! If they are general, like some common structure from sensor_msgs or a single float, perhaps a float array from std_msgs then you could even submit a PR with these changes and we can take them on oard as official components here!
