### ISSUE TITLE
Dynamically tuning [joint_trajectory_controller] PID gains

### ISSUE THREAD

**Issue by rafiqrana** [ros-controls/ros2_controllers#754]
Just wondering whether `ros2_controllers`  PID gains can dynamically be tuned using `rqt_reconfigure`. As far as I know, it works in ROS1 but not sure about ROS2.

I want to tune dynamically PID gains.[p/i/d] for each of the joints while the `joint_trajectory_controller` is run. I tried using `rqt_reconfigure` to tune each PID gain but nothing happened.

**Comment by bmagyar** [comment]
Original intent was that they are tunable so they should be.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: rafiqrana ***@***.***>
Sent: Wednesday, August 23, 2023 1:03:36 PM
To: ros-controls/ros2_controllers ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ros-controls/ros2_controllers] Dynamically tuning [joint_trajectory_controller] PID gains (Issue #754)


Just wondering whether ros2_controllers PID gains can dynamically be tuned using rqt_reconfigure. As far as I know, it works in ROS1 but not sure about ROS2.

I want to tune dynamically PID gains.[p/i/d] for each of the joints while the joint_trajectory_controller is run. I tried using rqt_reconfigure to tune each PID gain but nothing happened.

**Comment by christophfroehlich** [comment]
I think this was not ported with #384. Now they only get updated at on_init and on_configure.

I'll have a look how to activate that again with the generate_parameter_library.
