### ISSUE TITLE
steering controller library (ackermann steering) does not publish odom TF

### ISSUE THREAD

**Issue by guidout** [ros-controls/ros2_controllers#762]
**Describe the bug**
I see the following topics:
/ackermann_steering_controller/controller_state
/ackermann_steering_controller/odometry
/ackermann_steering_controller/reference
/ackermann_steering_controller/tf_odometry
/ackermann_steering_controller/transition_event
but the odom transform is not being published.

**Environment:**
 - OS: Ubuntu 22.04
 - Version: Humble

**Comment by Corund060** [comment]
/ackermann_steering_controller/tf_odometry is odom tf, remap to /tf

**Comment by guidout** [comment]
I tried that but it doesn't seem to apply. Maybe I have an error in the launch file?
Here is how I'm launching the controller in my launch file:
```
ackermann_steering_controller_spawner = Node(
       package="controller_manager",
       executable="spawner",
       parameters=[{'use_sim_time': use_sim_time}],
       arguments=["ackermann_steering_controller"],
       remappings=[('ackermann_steering_controller/tf_odometry','tf')],
       condition= IfCondition(LaunchConfiguration('use_ackermann_controller'))
    )
```

**Comment by Corund060** [comment]
You are remapping in the wrong place. You have to do it for ros2_control not for the spawner.

**Comment by guidout** [comment]
yes! that worked. Thank you so much.
Now that works for simulation, for the real robot I guess I have to had the remappings in ros2_control node like below, right?
```
controller_manager = Node(
        package="controller_manager",
        executable="ros2_control_node",
        parameters=[{'robot_description': robot_description},
                    controls_params_file,
                    controls_rear_wheels_params_file,
                    {'use_sim_time': use_sim_time}],
        remappings=[('ackermann_steering_controller/tf_odometry','tf')],
        condition= UnlessCondition(use_sim_time)
    )
```

**Comment by Corund060** [comment]
This should work. Haven't tested it myself though.

**Comment by christophfroehlich** [comment]
Yes this should be fine, see [this example](https://github.com/ros-controls/ros2_control_demos/pull/316) here.
