### ISSUE TITLE
Fatal Error: Missing 'rclcpp/event_handler.hpp' during Build of master

### ISSUE THREAD

**Issue by Andreasgdp** [ros-controls/ros2_controllers#783]
**Describe the bug**
When attempting to build the ros-controls repository using the `colcon build --symlink-install` command, a fatal error is encountered. The error message indicates that the file `rclcpp/event_handler.hpp` is missing or cannot be located.

**To Reproduce**
1. Clone repo
2. Build repo with `colcon build --symlink-install`
3. See that you get include error with `"rclcpp/event_handler.hpp"`

**Expected behavior**
The build process should proceed without any errors or missing file references.

**Screenshots**
![image](https://github.com/ros-controls/ros2_controllers/assets/39928082/90132545-6fe3-4e86-a7b2-de6e8f62459e)

**Environment:**
 - OS: Ubuntu 22.04
 - Version Humble

**Comment by gavanderhoorn** [comment]
Can you check you're building the `humble` branch?

Only `master` tries to `#include` that file.

**Comment by christophfroehlich** [comment]
> Can you check you're building the `humble` branch?
> 
> Only `master` tries to `#include` that file.

correct, there was an [upstream change](https://github.com/ros-controls/ros2_controllers/pull/610) of the header files from iron on, and the rolling-version (from master branch) won't build on a humble distro.

**Comment by Andreasgdp** [comment]
That was the issue, tanks
