### ISSUE TITLE
Incorrect odometry when turning vehicle with bicycle steering controller.

### ISSUE THREAD

**Issue by reydelsol** [ros-controls/ros2_controllers#789]
**Describe the bug**
Driving a robot with the bicycle steering controller produces incorrect odometry when turning.

**To Reproduce**
This was found during development of a hardware interface for a vehicle modeled with a bicycle controller. A minimal example is not provided, but appears to demonstrate similar behavior to #675. The bug is believed to stem from a mismatch of units in steering_odometry.cpp and may affect other ROS2 controllers:
1. The function update_odometry calls an integrate_exact function with inputs of linear change and angular velocity, `SteeringOdometry::integrate_exact(linear_velocity * dt, angular);`
   a. This differs from a call to the [same function in update_open_loop](https://github.com/ros-controls/ros2_controllers/blob/ca38c06f712663449ddf1372234d74a983b7d5f5/steering_controllers_library/src/steering_odometry.cpp#L184) which passes linear and angular change, `SteeringOdometry::integrate_exact(linear * dt, angular * dt);`
   b. The integrate_exact function calculates odometry’s heading_, x_, and y_ from a division of linear change and angular velocity. The heading_ angle is incremented by units of angular velocity. For a controller update rate of 100 Hz, dt = .01, the heading would change 100x faster than the reality.
   c. This issue was not found for a linear-only change, as  integrate_exact calls [integrate_runge_kutta_2](https://github.com/ros-controls/ros2_controllers/blob/ca38c06f712663449ddf1372234d74a983b7d5f5/steering_controllers_library/src/steering_odometry.cpp#L293) for near-zero angular change.

2. The function [update_from_velocity](https://github.com/ros-controls/ros2_controllers/blob/ca38c06f712663449ddf1372234d74a983b7d5f5/steering_controllers_library/src/steering_odometry.cpp#L147) appears to calculate the angular velocity.
   a. The equation matches that of [theta_dot for a bicycle](https://dingyan89.medium.com/simple-understanding-of-kinematic-bicycle-model-81cac6420357) kinematic model, 𝜃_dot = 𝑣 / (L / tan(𝛿)) = 𝑣 * tan(𝛿) / L
   b. The variable is named, “angular,” unlike the linear_velocity counterpart in this function. The unit 1/s appears to be lost as it is passed to integrate_exact() via update_odometry().
   c. Note that other calls to update_odometry in this file also pass “angular” to update_odometry, so the issue may affect other models.

**Expected behavior**
It is expected that the odometry would update at a slower rate and better represent the position of the robot’s dead reckoning. The odometry reported for our vehicle had it spin 5+ times in a circle within seconds (see screenshots).

**Screenshots**
The odometry appears to loop multiple times in 10 seconds, forming a circle:

![image](https://github.com/ros-controls/ros2_controllers/assets/7462508/c5a5a8aa-7c0f-4f27-b3dc-a82c76da86e6)

The expected behavior for a 20 degree steer would be more of a slope away from the forward direction:

![image](https://github.com/ros-controls/ros2_controllers/assets/7462508/22a97c0f-77a5-4488-8532-03ace1532292)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version: ROS2 Humble
 - Run in docker container on Ubuntu 22.04

**Additional context**
A [comment on this closed issue](https://github.com/ros-controls/ros2_controllers/issues/611#issuecomment-1551850475) may also be relevant, #611.

**Comment by christophfroehlich** [comment]
I tried to understand the code, but failed..

- In the header file, it is written that it should always be of unit `m` and `rad`, but it is called _velocity_.
https://github.com/ros-controls/ros2_controllers/blob/ca38c06f712663449ddf1372234d74a983b7d5f5/steering_controllers_library/include/steering_controllers_library/steering_odometry.hpp#L195-L201
- From update_from_position/update_from_velocity I'd say that both are velocities and not displacements.
https://github.com/ros-controls/ros2_controllers/blob/ca38c06f712663449ddf1372234d74a983b7d5f5/steering_controllers_library/src/steering_odometry.cpp#L156-L160
because docs say that inputs are rad/s and rad
https://github.com/ros-controls/ros2_controllers/blob/ca38c06f712663449ddf1372234d74a983b7d5f5/steering_controllers_library/include/steering_controllers_library/steering_odometry.hpp#L114-L124
- Why is there the tan() missing, comparing it to the other functions
https://github.com/ros-controls/ros2_controllers/blob/ca38c06f712663449ddf1372234d74a983b7d5f5/steering_controllers_library/src/steering_odometry.cpp#L172
- The library lacks any tests for these functions.

@reydelsol would you like to help to sort that stuff out, ideally including simple tests for the functions?

**Comment by christophfroehlich** [comment]
or maybe @petkovich is around and can clarify this?

**Comment by ARK3r** [comment]
I am also confused so I started studying the steering libraries, and I'll leave here what I find in hopes that this might be useful in expediting the process of implementing the proposal [here](https://github.com/ros-controls/ros2_controllers/issues/692):

- one confusing item I found was the difference between `reference_callback` and `reference_callback_unstamped` in the steering_controllers_library:

https://github.com/ros-controls/ros2_controllers/blob/f62fc3ac5f480b5a74765e642cd33d17600f7f5a/steering_controllers_library/include/steering_controllers_library/steering_controllers_library.hpp#L144-L146

should `reference_callback_unstamped` also get a `STEERING_CONTROLLERS__VISIBILITY_LOCAL`?

Also, in `reference_callback` we have:

https://github.com/ros-controls/ros2_controllers/blob/f62fc3ac5f480b5a74765e642cd33d17600f7f5a/steering_controllers_library/src/steering_controllers_library.cpp#L229-L232

but in `reference_callback_unstamped`, after making a new twist message we're never writing to `input_ref_`:

https://github.com/ros-controls/ros2_controllers/blob/f62fc3ac5f480b5a74765e642cd33d17600f7f5a/steering_controllers_library/src/steering_controllers_library.cpp#L265-L268

Am I missing something or is this a bug?

- Then, assuming the twist message has been saved, inside `update_reference_from_subscribers` we set reference_interfaces_ to the linear and angular components of the twist msg:

https://github.com/ros-controls/ros2_controllers/blob/f62fc3ac5f480b5a74765e642cd33d17600f7f5a/steering_controllers_library/src/steering_controllers_library.cpp#L411-L418

- Then, inside update_and_write_commands we run update_odometry which is [virtual inside steering_controllers_library](https://github.com/ros-controls/ros2_controllers/blob/f62fc3ac5f480b5a74765e642cd33d17600f7f5a/steering_controllers_library/include/steering_controllers_library/steering_controllers_library.hpp#L66C1-L67C42) and each steering controller should define for itself ([ackermann](https://github.com/ros-controls/ros2_controllers/blob/f62fc3ac5f480b5a74765e642cd33d17600f7f5a/ackermann_steering_controller/src/ackermann_steering_controller.cpp#L57-L91), [bicycle](https://github.com/ros-controls/ros2_controllers/blob/f62fc3ac5f480b5a74765e642cd33d17600f7f5a/bicycle_steering_controller/src/bicycle_steering_controller.cpp#L55C1-L80C2), and [tricycle](https://github.com/ros-controls/ros2_controllers/blob/f62fc3ac5f480b5a74765e642cd33d17600f7f5a/tricycle_steering_controller/src/tricycle_steering_controller.cpp#L55C1-L85C2)), which inside each update_odometry two seperate logics are implemented based on `open_loop` param being set to true or not.

   - If `open_loop` is true, odometry will update `x_`, `y_`, and `heading_`. I'm not sure if the calculations are correct considering the this current issue but I added a test [here](https://github.com/ARK3r/ros2_controllers/tree/odom_test) and the file can be found at `build/steering_controllers_library/odom_test` after `colcon build`. Two cases of going straight and moving-and-turning a little seem to be working correctly. With `open_loop` set to true, the `steering_odometry` object should strictly calculate `x_`, `y_`, and `heading_`, which to the best of my knowledge is what's being done, then each steering_controller subclass has to create values for all the joints it has available.
   - With [this PR](https://github.com/ros-controls/ros2_controllers/pull/793) a buggy piece of the code will also be fixed. 
   - If `open_loop` is false, then the values from the states should be read, and from them should the odometry be updated.

More investigation is needed to fully figure out the structure of the code before the proposal can be implemented, but I'm afraid I don't have the time to continue right now.

**Comment by christophfroehlich** [comment]
This should be fixed with https://github.com/ros-controls/ros2_controllers/pull/1150 et al. Please reopen if this still doesn't work out.
