### ISSUE TITLE
[JTC] home pose seems to be broken: explain, fix or remove?

### ISSUE THREAD

**Issue by christophfroehlich** [ros-controls/ros2_controllers#841]
JTC has code for a `home_pose`, but I think it is broken (and there is no test for it).

There are two shared pointers:
```c++
  std::shared_ptr<Trajectory> traj_home_point_ptr_ = nullptr;
  std::shared_ptr<trajectory_msgs::msg::JointTrajectory> traj_msg_home_ptr_ = nullptr;
```

- [`on_activate()` ](https://github.com/ros-controls/ros2_controllers/blob/3fc0f50c440ad49b2194b2c7dae8c54d6cda7b07/joint_trajectory_controller/src/joint_trajectory_controller.cpp#L924C6-L939)
   - `traj_msg_home_ptr_` is created and set to the position of the joint_state_interface
   - `traj_home_point_ptr_` created with an empty `std::make_shared<Trajectory>()` 
- Both will be resetted at `on_deactivate()`
https://github.com/ros-controls/ros2_controllers/blob/3fc0f50c440ad49b2194b2c7dae8c54d6cda7b07/joint_trajectory_controller/src/joint_trajectory_controller.cpp#L1031-L1032
- `on_cleanup()`:  would be used if not a `nullptr`
https://github.com/ros-controls/ros2_controllers/blob/3fc0f50c440ad49b2194b2c7dae8c54d6cda7b07/joint_trajectory_controller/src/joint_trajectory_controller.cpp#L1041-L1045

Am I right that: [lifecycle nodes](https://design.ros2.org/articles/node_lifecycle.html) have no possible transition from active state to unconfigured without `on_deactivate()`, which means that within `on_cleanup()` it can only hold `nullptr` and no action is performed?

Is there any rationale behind that or can it be deleted?

**Comment by saikishor** [comment]
Hello @christophfroehlich,

In my opinion, this can be removed. Moreover, I don't like the idea of the controller doing some activity of commanding joints when the intention is to deactivate or reconfigure. Instead, if I want the robot to have a certain home posture, I can always run the motion first and then deactivate it. 

https://github.com/ros-controls/ros2_control/blob/cf405bc3d3ad6c999a35a98faccf871a9b00c008/controller_manager/src/controller_manager.cpp#L2045

Moreover, the CM only updates the controllers that are currently in active mode, so even if we fix it, it might not execute at all.
